import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { CssBaseline, Stack } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Stack bgcolor="lightslategray" height={"100vh"} width={"100vw"}>
            <CssBaseline />
            <Stack
              alignItems="center"
              justifyContent="center"
              height="100%"
              width="100%"
            >
              <Stack
                height={600}
                width={400}
                bgcolor="#fff"
                p={2}
                borderRadius={2}
              >
                {children}
              </Stack>
            </Stack>
          </Stack>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
